sonar.organization=Huycon2352

sonar.projectKey=huycon2352code

sonar.projectName=Voting App Microservices

sonar.sources=vote,result,worker

sonar.sourceEncoding=UTF-8

# Bỏ qua thư mục build/cache nếu có
sonar.exclusions=**/node_modules/**,**/dist/**,**/bin/**,**/obj/**,**/__pycache__/**
