name: CI-Test-SONARQ

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prod

jobs:
  build-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
    
      - name: Install dependencies
        run: |
          cd vote
          pip install -r requirements.txt
          pip install pytest pytest-cov
    
      - name: Run tests
        working-directory: vote
        run: |
          PYTHONPATH=. pytest --cov=app --cov-report=xml
    
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_URL }}
        with:
          args: >
            -X
    
      # - name: Sonar Quality Gate
      #   uses: SonarSource/sonarqube-quality-gate-action@master
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
